# Generated by Django 5.2 on 2025-09-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_walk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('crypto_selection', models.CharField()),
                ('crypto_price', models.IntegerField()),
                ('number_of_coins_purchased', models.IntegerField()),
                ('stock_selection', models.CharField()),
                ('stock_price', models.IntegerField()),
                ('number_of_stock_purchased', models.IntegerField()),
            ],
        ),
    ]
