# Generated by Django 5.2 on 2025-09-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_walk', '0002_selections'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySelections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('crypto_1', models.CharField()),
                ('crypto_1_selections', models.IntegerField(default=0)),
                ('crypto_2', models.CharField()),
                ('crypto_2_selections', models.IntegerField(default=0)),
                ('stock_1', models.CharField()),
                ('stock_1_selections', models.IntegerField(default=0)),
                ('stock_2', models.CharField()),
                ('stock_2_selections', models.IntegerField(default=0)),
            ],
        ),
    ]
