# Generated by Django 5.2 on 2025-09-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_walk', '0003_dailyselections'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyselections',
            name='crypto_1_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyselections',
            name='crypto_2_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyselections',
            name='stock_1_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyselections',
            name='stock_2_price',
            field=models.IntegerField(default=0),
        ),
    ]
