# Generated by Django 5.2 on 2025-09-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_walk', '0004_dailyselections_crypto_1_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyselections',
            name='crypto_1_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyselections',
            name='crypto_2_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyselections',
            name='stock_1_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyselections',
            name='stock_2_price',
            field=models.FloatField(default=0),
        ),
    ]
