# Generated by Django 5.2 on 2025-09-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_walk', '0005_alter_dailyselections_crypto_1_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('crypto_portfolio_value', models.FloatField(default=10000)),
                ('stock_portfolio_value', models.FloatField(default=10000)),
            ],
        ),
        migrations.AlterField(
            model_name='selections',
            name='crypto_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='selections',
            name='stock_price',
            field=models.FloatField(),
        ),
    ]
