# Generated by Django 5.2 on 2025-09-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_walk', '0006_portfolio_alter_selections_crypto_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='crypto_cash',
            field=models.FloatField(default=10000),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='stock_cash',
            field=models.FloatField(default=10000),
        ),
    ]
